// @ts-expect-error: it is a script so noneed of error check

import { readdirSync, statSync, writeFileSync } from 'fs';
import { join, relative } from 'path';

const DOCS_DIR = 'src/routes/docs';
const OUTPUT = 'src/routes/docs/nav.ts';
const PINNED = ['introduction', 'getting-started'];
function scan(dir, base = '') {
	const entries = readdirSync(dir, { withFileTypes: true }).filter(
		(e) => !['nav.ts', '+layout.svelte', '+layout.ts'].includes(e.name)
	); // ignore layout files

	const links = [];
	let hasDirectPage = false;

	for (const entry of entries) {
		const fullPath = join(dir, entry.name);

		if (entry.name === '+page.md' || entry.name === '+page.svx') {
			hasDirectPage = true;
		} else if (entry.isDirectory()) {
			const children = scan(fullPath, join(base, entry.name));
			if (children.length === 1 && !children[0].links) {
				links.push(children[0]);
			} else if (children.length) {
				const heading = entry.name.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
				links.push({ heading, links: children });
			}
		}
	}

	// add direct page link at the top of this level
	if (hasDirectPage) {
		const href = '/docs' + (base ? '/' + base.replace(/\\/g, '/') : '');
		const slug = base.split(/[\\/]/).pop() ?? '';
		const label = slug
			? slug.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
			: 'Introduction';
		links.unshift({ label, href });
	}
	links.sort((a, b) => {
		if (a.label === 'Introduction') return -1;
		if (b.label === 'Introduction') return 1;
		const aSlug = (a.href ?? '').split('/').pop() ?? '';
		const bSlug = (b.href ?? '').split('/').pop() ?? '';
		const aPin = PINNED.indexOf(aSlug);
		const bPin = PINNED.indexOf(bSlug);

		if (aPin !== -1 && bPin !== -1) return aPin - bPin; // both pinned, keep pin order
		if (aPin !== -1) return -1; // a pinned
		if (bPin !== -1) return 1; // b pinned
		return aSlug.localeCompare(bSlug);
	});

	return links;
	return links;
}

const nav = scan(DOCS_DIR);

function serializeLink(link) {
	return `{ label: '${link.label}', href: '${link.href}' }`;
}

function serializeItem(item) {
	if (item.links) {
		const links = item.links.map(serializeLink).join(',\n        ');
		return `{\n        heading: '${item.heading}',\n        links: [\n        ${links}\n        ]\n    }`;
	}
	return serializeLink(item);
}

const serialized = nav.map(serializeItem).join(',\n    ');

const output = `// AUTO-GENERATED by scripts/gen-docs.js — do not edit manually
export type NavLink = { label: string; href: string };
export type NavSection = { heading: string; links: NavLink[] };
export type NavItem = NavLink | NavSection;

export const nav: NavItem[] = [
    ${serialized}
];
`;

writeFileSync(OUTPUT, output);
console.log(`nav.ts generated `);
